name: TransmitGenerators
version: '${project.version}'
main: mc.warp.transmitgenerators.TransmitGenerators
api-version: 1.17
authors: [ mowmowkittycar ]
description: A Minehut Style Generator Plugin created by mowmowkittycar
depend: [ IdleCore ]
softdepend: [ PlaceholderAPI ]
commands:
  TransmitGen:
    aliases: tg